#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"

# 软链日志文件
echo "$(date '+%Y-%m-%d %H:%M:%S') - 开始配置日志文件软链..." >> "${LOG_FILE}"
mkdir -p "/var/apps/yuexps.2fmusic/shares/2FMusic" >> "${LOG_FILE}" 2>&1
rm -rf "/var/apps/yuexps.2fmusic/shares/2FMusic/info.log" >> "${LOG_FILE}" 2>&1
ln -sf "${LOG_FILE}" "/var/apps/yuexps.2fmusic/shares/2FMusic/info.log" >> "${LOG_FILE}" 2>&1

echo "$(date '+%Y-%m-%d %H:%M:%S') - 安装完成" >> "${LOG_FILE}"
exit 0