#!/bin/bash

### This script is called after the user uninstalls the application.

wizard_data_action="$wizard_data_action"

if [ "${wizard_data_action}" = "delete" ]; then
    rm -rf "${TRIM_PKGVAR}"
    if [ -d "/var/apps/yuexps.2fmusic/shares/2FMusic" ]; then
        rm -rf /var/apps/yuexps.2fmusic/shares/2FMusic/*
    fi
fi

exit 0