#!/bin/bash

CONFIG_FILE="${TRIM_APPDEST}/ui/js/config.js"
if [ -n "${wizard_password}" ]; then
    echo "window.PRECONFIGURED_PASSWORD = \"${wizard_password}\";" > "${CONFIG_FILE}"
fi
chmod 644 "${CONFIG_FILE}"
exit 0